### ISSUE TITLE
Dev Errors: Some weird Null Pointer issue

### ISSUE THREAD

**Issue by vidzi** [scupid-admin/Morph.ai-Support#98]
```[2018-10-22 21:44:06.422] [SimpleBrandSpecificThreadPoolOurExecutorService-9|Morph_null_null] [ERROR] [c.a.b.e.b.AbstractThreadPoolOurExecutorService] [] [com.altin.base.excpetion.OurRuntimeException: id: 5bce44642639a3ef268e5fe6 message id 5bce44a6edc1587d23549325
at com.altin.base.utilities.OurExceptionUtils.createOrGetRuntimeException(OurExceptionUtils.java:114)
at com.altin.base.utilities.OurExceptionUtils.createOrGetRuntimeException(OurExceptionUtils.java:109)
at com.altin.ME.v2.processor.MEProcessor.runForBrand(MEProcessor.java:69)
at com.altin.base.executor.base.AbstractThreadPoolOurExecutorService$BrandSpecificRunnable.run(AbstractThreadPoolOurExecutorService.java:143)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at com.altin.base.executor.base.AbstractBrandSpecificThreadPoolOurExecutorService$1.runForBrand(AbstractBrandSpecificThreadPoolOurExecutorService.java:38)
at com.altin.base.executor.base.AbstractThreadPoolOurExecutorService$BrandSpecificRunnable.run(AbstractThreadPoolOurExecutorService.java:143)
at com.altin.base.executor.base.AbstractThreadPoolOurExecutorService.lambda$execute$0(AbstractThreadPoolOurExecutorService.java:76)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.altin.base.excpetion.OurRuntimeException: mId: 5bce44a6edc1587d23549325
at com.altin.base.utilities.OurExceptionUtils.createOrGetRuntimeException(OurExceptionUtils.java:114)
at com.altin.base.utilities.OurExceptionUtils.createOrGetRuntimeException(OurExceptionUtils.java:109)
at com.altin.morphbase.io_controller.MessageExecutorEngine.execute(MessageExecutorEngine.java:101)
at com.altin.ME.v2.processor.MEProcessor.executeMessage(MEProcessor.java:76)
at com.altin.ME.v2.processor.MEProcessor.runForBrand(MEProcessor.java:65)
... 9 common frames omitted
Caused by: java.lang.NullPointerException: null
at com.altin.morphbase.flow.resolution.ConversationResolutionService.updateContext(ConversationResolutionService.java:262)
at com.altin.morphbase.flow.resolution.ConversationResolutionService.resolveConversation(ConversationResolutionService.java:104)
at com.altin.morphbase.io_controller.MessageExecutorEngine.execute(MessageExecutorEngine.java:93)
... 11 common frames omitted
]```

**Comment by vidzi** [comment]
This has been fixed
